export const cmsBlueprint = {
  page: ["title", "slug", "seo", "sections", "hero", "navigationVisibility"],
  service: [
    "title",
    "navTitle",
    "slug",
    "seo",
    "heroTitle",
    "subtitle",
    "summary",
    "image",
    "sections",
    "ctas",
    "bookingFormType",
  ],
  teamMember: [
    "name",
    "slug",
    "role",
    "photo",
    "bio",
    "qualifications",
    "serviceAssociations",
    "socialLinks",
    "publish",
  ],
  blogPost: [
    "title",
    "slug",
    "category",
    "author",
    "publishedAt",
    "heroImage",
    "excerpt",
    "body",
    "relatedPosts",
    "seo",
  ],
  bookResource: [
    "title",
    "slug",
    "coverImage",
    "description",
    "purchaseLinks",
    "resourceType",
    "publish",
  ],
  testimonial: ["quote", "name", "role", "organisation", "service", "publish"],
  partner: ["name", "logo", "url", "publish"],
  formSubmissionMetadata: [
    "type",
    "receivedAt",
    "consent",
    "deliveryStatus",
    "noSensitiveDetailsStored",
  ],
  seoFields: ["title", "description", "openGraphImage", "noIndex"],
};
